### PR TITLE
Use apt to upgrade Procursus packages automatically

### PR DESCRIPTION
**Pull request by deontw**
Also run uicache on Loader app

### CODE REVIEW

**Comment by deontw** [comment]
截圖 2021-08-30 上午12 04 32
截圖 2021-08-30 上午12 04 49
截圖 2021-08-30 上午12 05 02
Also should fix the Loader app disappear sometimes on iOS 14.

**Comment by deontw** [comment]
Well, it should fix Loader app sometimes disappear on iOS 14.

**Comment by asdfugil** [comment]
Why insecure

**Comment by deontw** [comment]
Oh yeah that's many fault. I just a little bit afraid that refresh failed

**Pull request merged**
