### PR TITLE
Update bootstraps, install Sileo 2.0, and add in iOS 14 bootstrap

### PR DESCRIPTION
**Pull request by marijuanARM**
GitHub didn't want to update the previous PR to include my latest commit -.-

### CODE REVIEW

**Comment by coolstar** [comment]
libswift isn't needed on iOS 12.2 or higher FYI

Should only install it on 12.1.4 or lower

**Comment by marijuanARM** [comment]
whoops, didn't mean to include 12.2

**Review by coolstar — APPROVED** [review]
Looks good to me. Let's get someone to test this and it's good to go

**Comment by marijuanARM** [comment]
Tested on an iPod touch 6 on 12.4.8, works fine there.

**Pull request merged**
