### PR TITLE
Re-add executable bit on procursus-deploy-linux-macos.sh

### PR DESCRIPTION
**Pull request by 0xallie**
@deontw was a dumbass and removed it

### CODE REVIEW

**Comment by deontw** [comment]
> @deontw was a dumbass and removed it



> @deontw was a dumbass and removed it

IMG_3043

**Comment by deontw** [comment]
> @deontw was a dumbass and removed it

IMG_3043

**Comment by manrand** [comment]
@nyuszika7h if this was `force-pushed` do we still need it here?

**Comment by manrand** [comment]
Got it, thanks

**Pull request merged**
