### PR TITLE
Fix Odysseyra1n deploy script on M1

### PR DESCRIPTION
**Pull request by Doregon**
M1 returns arm64 with uname -m, wheras iOS devices return the model identifier of the device.

### CODE REVIEW

**Comment by Doregon** [comment]
This fixes #28

**Comment by hopolapopola** [comment]
another way would be to check for the identifier itself, i.e. for iPhone/iPad/iPod since afaik this can't strap an apple tv

**Comment by Doregon** [comment]
> another way would be to check for the identifier itself, i.e. for iPhone/iPad/iPod since afaik this can't strap an apple tv

This is true. I just found it to be less complicated to use !arm64 and !x86_64 because all Macs return the CPU architecture with `uname -m`.

**Comment by nyuszika7h** [comment]
I didn't notice this PR, but in mine I decided to check `sw_vers` instead.

> afaik this can't strap an apple tv

It kinda can, though it's partially broken using the iOS strap.

**Pull request closed without merging**
